### ISSUE TITLE
Improvement in License section

### ISSUE THREAD

**Issue by marcoXbresciani** [RichardLitt/standard-readme#100]
Following GNU project / FSF requirements I received for my projects on Savannah (NonGNU) software forgery (https://savannah.nongnu.org/users/marcobresciani) I think there is room for License section improvement.

1. There should be a license for the README.md as well, for example the GNU All-Permissive License (see https://www.gnu.org/licenses/license-list.en.html#GNUAllPermissive) or the GNU FDL (see https://www.gnu.org/licenses/fdl.html) if the file itself is longer than 300 lines, as suggested by FSF (see https://www.gnu.org/prep/maintain/html_node/License-Notices-for-Other-Files.html), so that the file itself has a license.

2. If the GNU FDL is used, a "GNU Free Documentation License" section is needed according to the license itself (see https://www.gnu.org/licenses/fdl.html#addendum: 

> A copy of the license is included in the section entitled "GNU Free Documentation License".

).

3. For (free) software projects (following Savannah requirements) should be mandatory to add third parties licenses so to properly document all dependencies. In a project I'm working on, for example, I've added something like
  ```markdown
  ## License
  GNU General Public License v3.0 or later Marco Bresciani
  ```
  This follows Standard Readme Style. Then I've added:
  ```
  This section also lists all the copyright notes for third parties
  components used in this project.

  Copyright (C)  2019  Marco Bresciani.

  Permission is granted to copy, distribute and/or modify this document
  under the terms of the GNU Free Documentation License, Version 1.3 or
  any later version published by the Free Software Foundation; with no
  Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts. A
  copy of the license is included in the section entitled "GNU Free
  Documentation License".
  ```
  And then a subsection for each dependency, with a couple of lines stating the license and the official link (on dependency site), that reports the license itself. For example:
  ```markdown
  ### Official GPL Logo
  These images are in the public domain. See
  https://www.gnu.org/graphics/license-logos.html.en.
  ```
  And then I've added a subsection (of License section) called GNU Free Documentation License, 
  copying the whole markdown file of the GNU FDL.

**Comment by RichardLitt** [comment]
I understand where you're coming from, but this only really holds for GNU licenses. I want to make Standard Readme license agnostic, and I think that the current license section works well enough _for the purposes I envisioned standard-readme resolving_. For your own READMEs, you may want to extend it in the way you suggest above, which is totally cool. However, I don't think we need to update the license section at the moment. 

Thank you.
