### ISSUE TITLE
Question on Usage section

### ISSUE THREAD

**Issue by marcoXbresciani** [RichardLitt/standard-readme#101]
I have a long (>600 lines) USAGE.md file (*) that becomes even longer (>1000 lines) due to adding its own GNU FDL license (as per the license itself: 

> A copy of the license is included in the section entitled "GNUFree Documentation License".

).

Is it reasonable (a.k.a. compliant with the Standard Readme Style) to have it in a separate file and simply add this Usage section:
```markdown
## Usage
See [USAGE.md](USAGE.md) file.
```
?

(*) The project itself is a spreadsheet with metrics and charts, so the USAGE.md describes, for all sheets, all relevant columns, formulas and charts...

**Comment by RichardLitt** [comment]
That definitely sounds fine to me. I don't think this needs to be specified in the standard - you're including information on how to use it, by directing people to better docs. That sounds great.
