### ISSUE TITLE
Question: clarifying on rules for install, usage, and contributing

### ISSUE THREAD

**Issue by sehwol** [RichardLitt/standard-readme#105]
Hello, I have two questions.

## Under what sections the following items should be put in?

Suppose I need to include the following information in the *README.md* for a web app (backend and frontend code).

- Development prerequisites (e.g. supported IDE, database Docker image).
- How to run the web app locally (e.g. configuring ports).
- Common gotchas devs may encounter while trying to run locally/working (e.g. `ng serve` running out of memory, weird UI bugs).

Would I put these all under the Contributing section or is there some other section/subsection you would prefer? 

## What to put in the Usage section for web apps?

What should I put in the Usage section for web apps (not including Web APIs)?

**Comment by RichardLitt** [comment]
Standard Readme doesn't work very well for standard web apps. I would put all of your notices about development into a section called Develop, to be honest. I wouldn't use Contribute - those are things that are kind of secondary to how to contribute back. 

As for the usage and install, I'm not sure that it makes sense to have those sections for a webap. I would probably nix them.

**Comment by sehwol** [comment]
Sorry for the late reply.

Thanks for the clarification, I think that fully answers both questions.

**Comment by RichardLitt** [comment]
No worries. Open source means no expectations for time. Glad I could help, take care.
