### ISSUE TITLE
Provide a default for external api reference

### ISSUE THREAD

**Issue by dignifiedquire** [RichardLitt/standard-readme#12]
Some projects use external api documentation, the might be generated like go-doc or hand written like js-ipfs-api in `API.md`. It would be good to have some rules around how in this case the API section should look like.

**Comment by RichardLitt** [comment]
That would be good. The issue is that I don't want this to be language-specific; listing that seems like a sure way to end up bikeshedding. I am more interested in the entire README; What's within the sections matters a bit less to me.

**Comment by dignifiedquire** [comment]
Makes sense, maybe just add a note the API section description that this could simply be a link to an external reference?

**Comment by RichardLitt** [comment]
I think that is a good compromise.
