### ISSUE TITLE
Introduce REUSE compliance/compatibility

### ISSUE THREAD

**Issue by marcoXbresciani** [RichardLitt/standard-readme#124]
It would be nice to also add [REUSE](https://reuse.software/) compliance for licensing purposes.

This would add a more clear step in describing licenses.

**Comment by wooorm** [comment]
REUSE seems to suggest adding a comment to the start of a readme, I believe? It’s more about licenses per file, whereas standard-readme defines how to describe the license for the whole project?

I’d say I don’t think standard-readme should force everyone to use REUSE.
