### ISSUE TITLE
README, Markdown and other formats

### ISSUE THREAD

**Issue by marcoXbresciani** [RichardLitt/standard-readme#134]
Hello,
  just a question: why "forcing" the `.md` and the markdown format?
Is it simply because GitHub supports it?
Why not allowing also, for example, Orgmode (that is also supported by GitHub) or other formats like Asciidoc or similar?

Thanks.

**Comment by RichardLitt** [comment]
> Is it simply because GitHub supports it?

Seems easier to make a single standard. Could hypothetically change it. PRs accepted.
