### ISSUE TITLE
The "Install" section may not seem right for deployable websites

### ISSUE THREAD

**Issue by Ainali** [RichardLitt/standard-readme#142]
We were using the specification [up until recently](https://github.com/govdirectory/website/pull/274) when we decided that the name for the `Install` section didn't really sound right for our project, since it is a project with a website rather than software to install.

We therefore opted for what, we felt, was a more pedagogical header `Development setup`. Could that become an alternative name for the `Install` section?

**Comment by waldyrious** [comment]
I think "Install" and "Development setup" refer to different concepts — for example, a software project may have both sections, for users vs contributors. I'd note that the Install section is already [optional for documentation repositories](https://github.com/RichardLitt/standard-readme/blob/main/spec.md#install), so I would propose that exception to be broadened to include any project that doesn't require installation (e.g. websites/web apps that one just needs to visit their URL to access them).

On a separate note, I do agree that "Development setup" is a pretty relevant section for most software-related projects, so perhaps it could be explicitly mentioned as an example in the [Extra Sections](https://github.com/RichardLitt/standard-readme/blob/main/spec.md#extra-sections) part of the spec, or even included as one of the recommended sections (alongside e.g. "API").

**Comment by RichardLitt** [comment]
I think this may just be out of scope. 

> Standard Readme is designed for open source libraries. Although it’s [historically](https://github.com/RichardLitt/standard-readme#background) made for Node and npm projects, it also applies to libraries in other languages and package managers.

Web sites aren't libraries. You may need a different standard. Your fix seems fine to me, if noncompliant. 

Thanks, @Ainali! Good seeing you the other day.
