### ISSUE TITLE
Table of Contents Built in to GitHub

### ISSUE THREAD

**Issue by danyeaw** [RichardLitt/standard-readme#144]
A couple of years ago, GitHub added a feature to automatically generate a Table of Contents:
https://github.blog/changelog/2021-04-13-table-of-contents-support-in-markdown-files/

Even for a longer README, do you think creating a manual one inside the README is still important?

**Comment by waldyrious** [comment]
I do think a generic standard for README files should not rely on any particular code hosting platform's features. A ToC would still be useful for projects hosted elsewhere.

**Comment by danyeaw** [comment]
Fair enough, I agree making the ToC hosting independent is a good idea.
