### ISSUE TITLE
Back to Top link

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/standard-readme#16]
@tunnckoCore, [here](https://github.com/feross/standard/issues/141#issuecomment-221998673):

> one more thing: requirement - "each section must include 'back to top' link", would be great!

Hmm I haven't seen this much! Might be cool, but also adds noise. Maybe optional?

**Comment by tunnckoCore** [comment]
What noise? Navigation would make more sense and would be more easy.
Look at https://github.com/peterramsing/lost for example.

**Comment by RichardLitt** [comment]
Noise in a minimal readme - pretty wary about requirements if they don't add a ton. These links aren't usable from a CLI, and they have no use there - the ToC, while not usable from the terminal, can be used as a reference to see what is in the doc, and so is justified there as a link. 

I think that these can be optional, no problem with that at all.

**Comment by tunnckoCore** [comment]
> I think that these can be optional, no problem with that at all.

Yea okey, optional. I would be great to list in the spec to remind people ;]
