### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/standard-readme#17]
I added a requirement that the Contribute section should link to the Code of Conduct. Normally, this is in a separate document or in the Contribute.md, as far as I've seen before. 

Should we provide suggestions? 

Also, what code of conduct should we use? I know there are some standards, like the Contribute covenant http://contributor-covenant.org/version/1/3/0/.

**Comment by tunnckoCore** [comment]
It shouldn't be requirement, imo.

**Comment by RichardLitt** [comment]
@tunnckoCore I think it should be - it influences how people view, use, and contribute to your project. A lot of people need to know there is a safe space before they're going to use your code. 

This might be helpful! http://www.ashedryden.com/blog/codes-of-conduct-101-faq

**Comment by RichardLitt** [comment]
Thinking about the modularity aspect -- a CoC may be more important for pan-organization things, maybe not for individual modules which need a README. @noffle what do you think?

**Comment by tunnckoCore** [comment]
> not for individual modules

Exactly. I think contributing file is enough for most cases.

**Comment by noffle** [comment]
Agreed.

**Comment by RichardLitt** [comment]
Made optional.
