### ISSUE TITLE
"Install" and "Usage" sections aren't relevant for document repos

### ISSUE THREAD

**Issue by JesseWeinstein** [RichardLitt/standard-readme#21]
For repos like github.com/ipfs/specs , the "Install" and "Usage" sections aren't relevant -- but the standard-readme spec requires them. This should probably be adjusted.

**Comment by RichardLitt** [comment]
I agree 100%. I'll add a note that if there is no code, these are not relevant.

**Comment by RichardLitt** [comment]
@JesseWeinstein Satisfied? May close this.

**Comment by JesseWeinstein** [comment]
Yep.
