### ISSUE TITLE
Measure standard-readme's impact

### ISSUE THREAD

**Issue by daviddias** [RichardLitt/standard-readme#24]
It would be amazing to have a way to infer the impact of adopting standard-readme, to make sure that it not only improves the quality of a project, and therefore more usage, but also opens the floor for innovation (A/B testing). This will also validate standard-readme goal.

Things like [nodei.co](https://nodei.co/) or [Github Analytics](https://github.com/blog/1672-introducing-github-traffic-analytics) will be good sources to capture and visualize the growth and infer if there is any correlation.

**Comment by RichardLitt** [comment]
I agree with this. I don't think that nodei.co will work - people don't have to install the spec, currently, to make it work, but it will make sense when we have a linter. 

GitHub analytics can certainly help, although I wish I had more granularity in the referring column. 
<img width="1066" alt="screen shot 2016-07-28 at 2 02 45 pm" src="https://cloud.githubusercontent.com/assets/910753/17223753/fdf49a38-54cb-11e6-939b-04dfe7df20cd.png">

**Comment by davidak** [comment]
You could search on GitHub and other code hosting sites, for example for `![standard-readme compliant]`.

https://github.com/search?p=2&q=%22%21%5Bstandard-readme+compliant%5D%22&type=Code

So at least 1,849 repos have the badge.

But you don't see how many READMEs you influenced this way.

**Comment by RichardLitt** [comment]
Yeah! I have used that metric before. It works. I suspect the actual number is probably much higher.

**Comment by wooorm** [comment]
2,742 projects now (and 2.3k stars! I didn’t know it was getting so popular!)

> Yeah! I have used that metric before. It works. I suspect the actual number is probably much higher.

True

---

Closing this, don‘t think there's a better way to track it, and we can get this count now!
