### ISSUE TITLE
Top Header Naming: Should it always match the folder name?

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/standard-readme#26]
I am not convinced that the README's top header 100% needs to match the name of the module perfectly. 

Example: `standard`'s README could be labelled `# standard`, or `# Javascript Standard Style`. The same follows for `# standard-readme` or `# Standard Readme`. 

On the one hand, it _should_ match what the module is named or called when you download it. However, that is why we have an install section, anyway - you shouldn't need to get this from the top title. As well, the top title should be human readable. It's the first very first thing a human looks at. Naming it for, more often than not, the overall folder or computational name - which may be slightly off what the module should be called, due to a busy ecosystem and a full namespace (the right name may have been taken already, for instance) - seems counter productive. 

Is there a way we can regulate how this name should look, to make sure it is similar? Besides using human judgement, I don't think so. That having been said, human judgement is a much more powerful tool than any linter, and is what drives this standard, anyway. 

The computational title should be gotten in the install section, anyway.

**Comment by RichardLitt** [comment]
After thinking about it a lot, I don't think it needs to match the project name - the name used in the folder, or in the package.json, or by the registry, or anywhere else. It should be the _human_ name for the project. We can use _human linting_ to make sure that the name is correct - this isn't something that always has to be coded. 

Will wait 1 week for debate before merging this into the specification.

**Comment by martinheidegger** [comment]
Actually: I think this might need some revisiting. I think the reason why one would like to have then name in the h1 would be to make clear that _this is the code you are looking for_. That doesn't invalidate the current pain - which is that a headline should contain something easy to understand. How about a switch: Either a h1 that contains the name:

# standard

or a title with the name right beside it (as sort of subtitle)

i.e.
---

```markdown
# JavaScript Standard Style _(standard)_
```

---

```markdown
_standard_
# JavaScript Standard Style
```
---

```markdown
# JavaScript Standard Style
_(standard)_
```

**Comment by RichardLitt** [comment]
I like this! I think that:

```md
# JavaScript Standard Style _(standard)_
```

Solves our problem, and looks nice.
