### ISSUE TITLE
The Existence of a Table of Contents

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/standard-readme#27]
### What

Some people have asked me why the Table of Contents is important. [Example](https://github.com/haadcode/orbit/pull/35#issuecomment-234778177). 
### Background

I've been getting some pushback about table of contents being mandatory. For small READMEs with minimal sections, I can understand why this is a friction point. The Table of Content takes up visual space. 

However, for longer READMEs, I think a Table of Contents is super important. It allows the reader to know what sections are included in the README at a glance, normally without scrolling down, unless the reading window is small (and, if it is small, a Table of Contents can help signpost whether it is worth scanning to the end or not). 

I suspect that most of the time a new module is discovered, it is discovered on GitHub these days - the Table of Contents provides an easy way to navigate a README.

**Comment by jbenet** [comment]
+1 to TOCs they're super useful in big readmes (and should be an error not
to have one I think past a certain character count)

I do agree TOCs for small readmes are not needed.

But for example, id prefer a TOC in orbit's readme cause it's pretty big
and I don't know what's all in it. I don't know the readme as well as
others.

**Comment by martinheidegger** [comment]
A TOC is useful once there are a significant amount of sections. I.e. a small readme doesn't need it. The Standard readme could require a "fold" meaning: There is a section with two up to 4 paragraphs required before the TOC. And the TOC excludes the information before the fold. The TOC should imho. also only be required when there are more than 3 `h2`'s but forbidden before that.

**Comment by RichardLitt** [comment]
As it currently is, the long description goes before the ToC, and can get rather long - it's not inaccurate to put a subsection in the long description (h3 or h4) and then a few more paragraphs. I think this is fine. I don't want to put a character limit on it, although that may be the right way to go. 

I don't want to limit the number of h2s, either, because there's nothing saying you can't have three hundred h3s in one h2. Perhaps an lower character bound of 1000, above which you need to have a ToC. 

Lines might be a better metric than characters.

**Comment by martinheidegger** [comment]
Actually
> because there's nothing saying you can't have three hundred h3s in one h2

I think that is worth being an issue. This is a really badly structured doc that makes no sense to read 😉

**Comment by RichardLitt** [comment]
Fair point. Consign long API headers to `API.md`.

**Comment by RichardLitt** [comment]
The ToC is now optional if your README is under 100 lines. I think this solves the issue elegantly.
