### ISSUE TITLE
Maintainers Section

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/standard-readme#30]
Oughtn't there to be one?

**Comment by martinheidegger** [comment]
Contributors/Maintainers/etc. is a tricky topic at NodeSchool. It is important but maintaining it is hard. I'd consider at least a link to maintainers/contributors mandatory.

**Comment by VictorBjelkholm** [comment]
I think having a maintainers section would be nice, but would also be hard to maintain. I think as a first step, it would be good to include the Lead/Captain at least, that would be responsible for the repository as a whole.

**Comment by RichardLitt** [comment]
Having a captain makes the most sense for me, but that term doesn't cut across multiple organizations. Same for lead. Maintainers, for me, means the main people in charge of a repository - not the contributors as a whole, but the few people in charge of a project. 

Maintaining a maintainers section is not difficult; with each switch, add one, or remove another. It is important as a place of logging who to contact. Maintaining contributors is much more noisy.

**Comment by RichardLitt** [comment]
@martinheidegger What do you think of #39?

**Comment by martinheidegger** [comment]
Basically okay. Will create another issue that improves upon this.

**Comment by RichardLitt** [comment]
I've been thinking about it, and I do not think that this should be _mandatory_. It is fine if it is optional. 

Why? Because many great modules do not need maintainers. If a module is UNIXy, it should do one thing, and that thing well. For some modules, this means that it effectively never needs to be updated. Having a maintainer puts under pressure on the creator to constantly be around, and I don't want to encourage that - I want to encourage people to make modules that maintain themselves. Of course, this doesn't apply to all modules! But having a requirement that this be in standard-readme seems to neglect these repos, which I am not happy with.

**Comment by martinheidegger** [comment]
Even very longing code should have a maintainers section. No matter how long it runs, bugs can be found that can even be critical and having someone to address them too is just good practice.

**Comment by RichardLitt** [comment]
For now, this is required. We can change this if people don't like it.
