### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by VictorBjelkholm** [RichardLitt/standard-readme#33]
Took a overview look at js-ipfs, saw that a requirements section was missing (issue here: https://github.com/ipfs/js-ipfs/issues/453) and thinking, everything based on standard-readme is missing the requirements. This should ideally be it's own section, before the installation.

Could look something like this:

## Requirements
* Ubuntu / OSX
* npm [version 3 or above]
* node [version 6 or above]
* python [version 2]

<hr/>
```markdown
## Requirements
* Ubuntu / OSX
* npm [version 3 or above]
* node [version 6 or above]
* python [version 2]
```

What do you think?

**Comment by RichardLitt** [comment]
I don't think that this is a necessary section for most packages; most already have a very clear way of installing them through a package manager, which clears up the majority of the requirements. I think that this belongs in the `Install` section, as it most relevant there. The current specification outlines this:

```
### Install
**Status:** Required by default, optional for doc modules.

**Requirements:**
- Code block illustrating how to install.

**Subsections:**
- `Dependencies`. Required if there are unusual dependencies or dependencies that must be manually installed.
- `Updating`. Optional.

**Suggestions:**
- Link to prerequisite sites for programming language: [npmjs](https://npmjs.com), [godocs](https://godoc.org), etc.
- Include any system-specific information needed for installation.
- If there is no code in the module - for instance, a document-based module - this section is not required.
```

Do you think this ought to be changed?

**Comment by VictorBjelkholm** [comment]
> I don't think that this is a necessary section for most packages; most already have a very clear way of installing them through a package manager, which clears up the majority of the requirements.

Not so sure about that. I know in javascript-land, it's important to know which nodejs version + which npm version that the module supports, in some cases on which OS the module can be run and also if it supports the nodejs environment and browser, or just one of them. Sometimes, some modules also have peer dependencies ("you need this package, but it's not included here").

Same goes for Python, where the version split between 2 and 3 is significant. About go, not sure about that...

However, I did miss that the `requirements` already was a part of the install, I think that's good enough since its already covered.

**Comment by RichardLitt** [comment]
> However, I did miss that the requirements already was a part of the install, I think that's good enough since its already covered.

Perhaps I could make this more prominent, by adding it as an optional subsection?
