### ISSUE TITLE
Suggestion: Disallow broken links

### ISSUE THREAD

**Issue by dikarel** [RichardLitt/standard-readme#34]
I've seen quite a few projects where the links in the readme do not work; this is disruptive when you want to evaluate libraries or troubleshoot.

Examples:
- A link or image that 404s
- Trying to link to a non-existent file in the repo
- Syntax errors

I feel that `no broken links` as a rule would be valuable

**Comment by RichardLitt** [comment]
I think this is a good idea. I've been using dkhamsing/awesome_bot to check links on a lot of repos, and it is pretty useful, but this should be human verified. 

Sometimes, people use links to non-existent files as stubs. I think this is inherently confusing and I'd rather there as no link, in those cases - you can't know before hand if the link will 404 or not.

**Comment by RichardLitt** [comment]
Want to PR this? I can bump the package after.

**Comment by dikarel** [comment]
Sure thing. Seeing as the linter is still in development, I take it that I just need to update the spec, yes?

**Comment by dikarel** [comment]
Like this? #35
