### ISSUE TITLE
Look into Verb

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/standard-readme#36]
Just found [verb](https://github.com/verbose/verb), might be a good way to build another generator that is less dependent on Yeoman (if needed) .

**Comment by tunnckoCore** [comment]
> Just found verb

Welcome. :) https://github.com/node-toolkit/artwork

Actually it depends. You may also be interested in and may look at @generate.
Best for me is `generate-standard-readme` name.

I mentioned `standard-readme` [generate/generate#3](https://github.com/generate/generate/issues/3#issuecomment-246166687) and [verb-generate-readme#10](https://github.com/verbose/verb-generate-readme/issues/10)

**Comment by RichardLitt** [comment]
I'm going to come back to this. For now, I don't think it is fully actionable.
