### ISSUE TITLE
Require that JS snippets use standard-js

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/standard-readme#37]
We can easily suggest, or require, that all javascript snippets conform to [standard](//github.com/feross/standard). This can be done using https://github.com/zeke/standard-markdown. 

However, this is no longer strictly about the README, which is why I think that this should be a suggestion, but not necessarily a requirement. What do you think?

**Comment by noffle** [comment]
What if the user could provide the name of a linter program? Perhaps look for a property named "lint" under "scripts" and run that?

**Comment by tunnckoCore** [comment]
Vote for suggestion. It not make sense to be requirement.

**Comment by RichardLitt** [comment]
We don't have any optional provisions for users, at the moment; there's no config for standard-readme, basically. So I'm not sure your suggestion works well, @noffle. 

Suggestion makes the most sense, for me. But it is partially standard-readme's job; the code snippets are part of the README. What I don't want is to enforce standard in the code-base, though.

**Comment by noffle** [comment]
One trick might be to opt-in by embedding an HTML comment hint into your markdown. Something like:

    
    ```js
    var foo = require('foo')
    
    console.log(foo(14))
    ```

This will prevent the hints from showing up in the rendered markdown, but make it easy to perform a pre-processing step in standard-readme that runs the program `standard` with the following code snippet on `stdin`.

**Comment by tunnckoCore** [comment]
Still don't make sense. It's not readme job. Exactly because there's already a tool for such thing, it's not make sense to couple tools - SoC for the win. :)

**Comment by martinheidegger** [comment]
The readme should contain example's linted in the same way as the code is linted in the rest of the project. I think that is a reasonable assumption.

**Comment by RichardLitt** [comment]
I am going to keep this language agnostic. I used @martinheidegger's suggestion, added it as a requirement.
