### ISSUE TITLE
How about change badge style like feross/standard ?

### ISSUE THREAD

**Issue by sotayamashita** [RichardLitt/standard-readme#44]
According to a background, this project is inspired by feross/standard. If I use standard code style and readme. Badges will be like this below:

 [![Standard - JavaScript Style Guide](https://img.shields.io/badge/code%20style-standard-brightgreen.svg)](http://standardjs.com/) [![standard-readme compliant](https://img.shields.io/badge/standard--readme-OK-green.svg?style=flat-square)](https://github.com/RichardLitt/standard-readme)

I would like to style standard readme badge below:

 [![Standard - JavaScript Style Guide](https://img.shields.io/badge/code%20style-standard-brightgreen.svg)](http://standardjs.com/) [![standard-readme compliant](https://img.shields.io/badge/readme%20style-standard-brightgreen.svg?style=flat-square)](https://github.com/RichardLitt/standard-readme)

What do you think ?

**Comment by RichardLitt** [comment]
I like this a lot! It also is clearer. 

Let's implement this in a few days; give time for other people to weigh in on it.

**Comment by sotayamashita** [comment]
@RichardLitt 
I can help it and I will create a PR.

**Comment by RichardLitt** [comment]
Oh, no! Feel free to make a PR. I'll just wait a couple of days to merge it. I try to move a bit slowly on this, so that people have time to comment if they want. :)

**Comment by sotayamashita** [comment]
Here is a list using old style design on GitHub. https://github.com/search?utf8=%E2%9C%93&q=https%3A%2F%2Fimg.shields.io%2Fbadge%2Fstandard--readme-OK-green.svg%3Fstyle%3Dflat-square&type=Code&ref=searchresults

**Comment by sotayamashita** [comment]
@RichardLitt still wait ?

**Comment by RichardLitt** [comment]
Alright! Merged. 

Now, we need to PR all of the existing badges, if possible. I wonder if there is a tool to do string substitution PRs across multiple repositories. Know of any?

**Comment by sotayamashita** [comment]
How about to create a bot like https://github.com/ReadmeCritic.  I am looking into how it works.

**Comment by sotayamashita** [comment]
**:bulb: Idea**
1. Create GitHub user to observe and create PR. 
2. Create list including repos written in standard style.
3. Start batch. If there is a problem, GitHub user will create a PR.
4. If new README is created. user should create PR to include its link into the list.

**Comment by sotayamashita** [comment]
@RichardLitt not sure but we do not want to send a lot of PR ...

**Comment by RichardLitt** [comment]
For now, let's just assume they are backwards compatible. I'll be making PRs to most of the repos that use it later this year; I can PR the rest of the repos that don't have it afterwards.
