### ISSUE TITLE
Badge vs Banner

### ISSUE THREAD

**Issue by ianwremmel** [RichardLitt/standard-readme#48]
I'm working on project to deal with maintenance of boilerplate across projects (readmes, package.json values, common tooling, etc). In the process of writing a readme parser, I think I've determined that it's impossible to determine if a single image between the title and the short description is a Banner or a Badge. Any ideas?

(It's still *very early*, but [here's what I'm working on](https://github.com/ianwremmel/boilerize))

**Comment by RichardLitt** [comment]
I doubt it is impossible; for one, a human can tell you if it is or isn't. Allow either a badge or an image in the banner section, but only one, like this:

```
# title

![]()

![]()![]()![]()
```

You can then use https://www.npmjs.com/package/is-badge to see if it is a badge or not, too.

**Comment by ianwremmel** [comment]
is-badge will definitely help, thanks!

The case I' was worried about is 

```markdown
# title

![]()

> Short Description
```

Other than looking at the image url, i'm reasonably confident there's no way for a program to determine if that's a badge or a banner. That said, between is-badge and the unlikelihood of one single badge, I think I can make a guess that's accurate most of the time. Thanks!
