### ISSUE TITLE
standard-readme's README is not standard-readme compliant

### ISSUE THREAD

**Issue by rhys-vdw** [RichardLitt/standard-readme#52]
At time of writing this repository's [README.md](https://github.com/RichardLitt/standard-readme/blob/f0ed009d70b88bd352dc08352d180242af6270ce/README.md) does not contain the [**required** Maintainers section](https://github.com/RichardLitt/standard-readme/blob/f0ed009d70b88bd352dc08352d180242af6270ce/spec.md#maintainers).

**Comment by RichardLitt** [comment]
You're right! I fixed this. Thank you.
