### ISSUE TITLE
Sharing mutual concerns → mutualizing?

### ISSUE THREAD

**Issue by davidbgk** [RichardLitt/standard-readme#53]
Hi @RichardLitt,

I was at the JS meetup yesterday in Montreal where you talked about the project, I initiated a similar approach with https://github.com/davidbgk/open-source-template/ two years ago.

Definitely not the same activity there but maybe some things to add/consider in your standard readme? Like ethics, language or financial.

**Comment by RichardLitt** [comment]
Hey! This is pretty cool. 

Ethics and financial are largely good for larger projects, not smaller modules. And language is an interesting one; I don't think about this much, as English is my native tongue. 

Perhaps we could add a "Related efforts" section, and link to this in there?
