### ISSUE TITLE
Feature: accepted shares count

### ISSUE THREAD

**Issue by Gertsch** [RichardLitt/standard-readme#55]
Hey guys,

it would be awesome to have an accepted shares counter.
What do you think?

**Comment by RichardLitt** [comment]
What do you mean by accepted shares? I'm a bit confused by this. :)

**Comment by RichardLitt** [comment]
One of the things you can do is to search GitHub for the badge. For instance:  https://github.com/search?q=%22standard-readme+compliant%22&type=Code&utf8=%E2%9C%93 shows 533 repos. 

https://github.com/search?p=3&q=%22standard-readme%22&type=Code&utf8=%E2%9C%93 shows over 1k. :D 

So, I think it's good to say it is out there, in the wild, working.
