### ISSUE TITLE
Question: “Must be new lines between each section” is ambiguous

### ISSUE THREAD

**Issue by wooorm** [RichardLitt/standard-readme#58]
In the [spec](https://github.com/RichardLitt/standard-readme/blob/master/spec.md#specification), the **requirements** section contains the line: “Must be new lines between each section”.

I perceive that as ambiguous, is this ok? (new lines)

~~~markdown
# standard-readme
## Install
```sh
npm install some-thing
```
## Usage
```sh
some = require('some-thing')
some.thing()
```
~~~

Or this? (blank lines)

~~~markdown
# standard-readme

## Install
```sh
npm install some-thing
```

## Usage
```sh
some = require('some-thing')
some.thing()
```
~~~

Or? (blank lines between blocks)

~~~markdown
# standard-readme

## Install

```sh
npm install some-thing
```

## Usage

```sh
some = require('some-thing')
some.thing()
```
~~~

Or even? (blank lines between blocks, double between sections)

~~~markdown
# standard-readme


## Install

```sh
npm install some-thing
```


## Usage

```sh
some = require('some-thing')
some.thing()
```
~~~

...and finally: should the spec be unambiguous in this case?

**Comment by RichardLitt** [comment]
Frankly, I'm not sure that new lines is needed - that's a markdown thing, not a spec thing. It shouldn't matter. I'd prefer blank lines between blocks (double blank lines is unnecessary), but the first and second example should also be valid.

**Comment by wooorm** [comment]
Should we drop it from the spec then?

**Comment by RichardLitt** [comment]
Makes sense to me. I can PR that.

**Comment by wooorm** [comment]
Sure, or I could do it too!

**Comment by RichardLitt** [comment]
Removed that line. :)
