### ISSUE TITLE
Question: “Sections must have the titles listed below, unless otherwise specified” is unclear

### ISSUE THREAD

**Issue by wooorm** [RichardLitt/standard-readme#59]
In the [spec](https://github.com/RichardLitt/standard-readme/blob/master/spec.md#specification), the **requirements** section contains the line: “Sections must have the titles listed below, unless otherwise specified“.

- Does that reference the “Extra sections” part?
- Is this the default so that the spec could later allow alternative names for sections?
- Can you use any heading, as long as you specify in the readme that it’s not compliant?

**Comment by RichardLitt** [comment]
That does not include extra sessions. It should apply to: Table of Contents, Security, Background, Install, Usage, Contribute, and License. Any other sections are allowed, in the right location (after Usage). You shouldn't be able to rename these, so I'm not sure what I meant by otherwise specified.

What do you think?

**Comment by wooorm** [comment]
Maybe:

> Sections must have the titles listed below. Other sections and titles can be included in the document outline between Usage and API.

`Usage` and `API` are both optional, so that’s why I added “in the document outline”

**Comment by RichardLitt** [comment]
Usage isn't optional. API is, though. Between Usage and Maintainers would work?

**Comment by wooorm** [comment]
For people reading along: this is asynchronously discussed here: https://github.com/RichardLitt/standard-readme/issues/66#issuecomment-344403175

**Comment by wooorm** [comment]
I think this can be closed, the spec is clearer now!
