### ISSUE TITLE
Create a Standard Readme generator

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/standard-readme#6]
This is the planning issue for the Standard Readme generator. It will most likely be based on [generator-nms](github.com/RichardLitt/generator-nms), a node scaffold developed by me that is based on @sindresorhus's [generator-nm](https://github.com/sindresorhus/generator-nm), using [yeoman](http://yeoman.io/). 

Please subscribe and discuss generator issues here, and open other issues for Standard Readme questions.

**Comment by RichardLitt** [comment]
I believe that this is done, with the creation today of: https://github.com/RichardLitt/generator-standard-readme. Now I just need to link it here.

**Comment by zkochan** [comment]
Have you seen this package - [package-json-to-readme](https://github.com/zeke/package-json-to-readme)? It doesn't follow the standard readme currently, but it has no dependency on yeoman.

I am working on a pull request to that package, that will allow to dynamically update the readme (like automatically generating the Table of Contents), and test it for correctness, using [mos](https://github.com/mosjs/mos)

**Comment by RichardLitt** [comment]
I haven't, looks cool - @zeke does great work. I don't think it'll work for this project, because it is fairly npm and js specific. I'm looking for a more general standard. 

mos looks cool, too, but it messes up the clean formatting of the Markdown formatting. Sure, it works on GitHub, but I'm not sure [that this](https://raw.githubusercontent.com/mosjs/mos/master/README.md) is what I want. I may be wrong. It also isn't as simple as just text. I think that [remark-lint](https://github.com/wooorm/remark-lint) is probably a cleaner way forward.

**Comment by zeke** [comment]
👋 

Sorry to keep you waiting on that PR, @zkochan. My wife just had a baby so I'm mostly offline!

**Comment by zkochan** [comment]
@zeke congratulations!! :fireworks: 

Actually the PR can wait, I want to add some improvements to it.

**Comment by balupton** [comment]
https://github.com/bevry/projectz has been around for a few years now and seems to already accomplish what this issue aims to do. It is used on all bevry and docpad repos. Plan is to extend it with a plugim system in the coming months. Happy to improve it as necessary.

**Comment by RichardLitt** [comment]
@balupton I disagree. That is a much more broad project. I don't think it follows the Unix philosophy of doing one thing only. 

It also replaces comment tags instead of working solely with the text - something that works for GitHub, but that leads to extra code that isn't relevant (say if reading from terminal). I think that's something I want to avoid here. 

====

Now that https://github.com/RichardLitt/generator-standard-readme exists, this can probably be closed.
