### ISSUE TITLE
Suggestion: “Back to Top” needs an example

### ISSUE THREAD

**Issue by wooorm** [RichardLitt/standard-readme#60]
“Back to top” may be useful (although browsers also often supply a feature for this, on mobile you can often click the top bar to scroll up). But maybe it’s more clear if there’s an example of that, or a link to a readme that uses it?

```markdown
A "[Back to Top](...)" link for longer sections can be useful, but is not required by any means.
```

**Comment by RichardLitt** [comment]
Removed. I don't like these, anyway, and I don't think this suggestion is helpful. Thanks for pointing this out!
