### ISSUE TITLE
Editorial: use pretty quotes (`“”`) instead of straight ones (`""`)

### ISSUE THREAD

**Issue by wooorm** [RichardLitt/standard-readme#63]
Maybe it’s just me, but I really like so-called “smart” quotes over "straight" ones.

I can whip up a PR for it!

**Comment by RichardLitt** [comment]
Unfortunately, this is the ABSOLUTE WRONG DECISION TITUS. 

 - Richard, author of [this excellent module, named “smart-to-dumb-quotes”](https://github.com/RichardLitt/smart-to-dumb-quotes).

:D

**Comment by RichardLitt** [comment]
But, for real: I don't think that using smart-quotes is a good move. Mainly because I think it puts onus on the contributors to find out how to use them. I don't naturally have them set up. I also think they can be finicky with the wrong quotes being chosen, and I don't think they add anything.

**Comment by wooorm** [comment]
Oh yeah I get that. Okay that’s fine!
