### ISSUE TITLE
Question: is standard-readme node and npm specific?

### ISSUE THREAD

**Issue by wooorm** [RichardLitt/standard-readme#64]
The “short description” section suggests a point:

- Use `npm show . description` to show the description from a local [npm](https://npmjs.com) package.

...and install suggests:

- Link to prerequisite sites for programming language: [npmjs](https://npmjs.com), [godocs](https://godoc.org), etc.

---

- Is standard-readme node and npm specific?
- Should there be a note somewhere that it is or isn't?
- Should we provide examples of other package managers and languages?

**Comment by RichardLitt** [comment]
This is not meant to be node specific. We should add a note that it isn't. I am a bit too close to the material to adequately change this one easily - can you PR where you think might be appropriate? 

Yes, providing other package managers makes sense, but we don't have to go overboard.

**Comment by wooorm** [comment]
How about something like this:

> Standard Readme is designed for open source libraries.  Although it’s [historically](#background) made for Node and npm projects, it also applies to libraries in other languages and package managers.

...in a paragraph just above [table of contents](https://github.com/RichardLitt/standard-readme#table-of-contents) in the readme, and again in the [spec.md](https://github.com/RichardLitt/standard-readme/blob/master/spec.md#specification) under the first paragraph, but now in a block quote prefixed with `Note: `

OK? If so, I’ll make a PR and we can continue talking there.

**Comment by RichardLitt** [comment]
Works for me! Make the PR. 👍
