### ISSUE TITLE
Add Resources List

### ISSUE THREAD

**Issue by wooorm** [RichardLitt/standard-readme#67]
This section contains the suggestion:

- Listing past maintainers is good for attribution, and kind.

An example of how to do that, or a link to a readme that does, may be useful?

**Comment by RichardLitt** [comment]
It might be, but I think it's OK not to. We could also link to other documents about contributors, too - for instance, [all-contributors](https://github.com/kentcdodds/all-contributors/) or [name-your-contributors](https://github.com/mntnr/name-your-contributors). But I think it's OK, here, to just suggest it.

**Comment by wooorm** [comment]
Alright!

There’s probably other places where we could link to tools, maybe in "Further reading" / "Resources" lists?

**Comment by RichardLitt** [comment]
That would work for me! They should be in the README, though, I believe - not in the spec.

**Comment by wooorm** [comment]
Alright, are you okay with renaming this issue to “Add list of resources” or something?

Maybe between “[Example Readmes](https://github.com/RichardLitt/standard-readme#example-readmes)” and “[Related Efforts](https://github.com/RichardLitt/standard-readme#related-efforts)”.

**Comment by RichardLitt** [comment]
@wooorm Still think this is necessary?

**Comment by wooorm** [comment]
Totally forgot what this is about, I think we’re fine without it!

**Comment by RichardLitt** [comment]
That's what I was thinking. :D
