### ISSUE TITLE
Suggestion: clarify “Code of Conduct” text

### ISSUE THREAD

**Issue by wooorm** [RichardLitt/standard-readme#68]
Currently, the definition of the Contribute sections contains a suggestion:

- Link to Code of Conduct. This is often in Contribute, or organization wide, so may not be necessary for each module.

I feel the last sentence is a bit vague: does it mean the link is in contribute? Or organisation wide? Or is there file in the repo? Or organisation wide?

...oh and maybe add something that it’s optional but highly recommended?!

**Comment by RichardLitt** [comment]
I've changed the wording a bit. I'm happy with it at the moment, and it should be clearer. Let me know if it isn't!
