### ISSUE TITLE
Suggestion: require an SPDX identifier in License section?

### ISSUE THREAD

**Issue by wooorm** [RichardLitt/standard-readme#69]
The [License](https://github.com/RichardLitt/standard-readme/blob/master/spec.md#license) section requires the point:

- State license initials or name.

Maybe defer to [SPDX](https://spdx.org/licenses/), just like [npm](https://docs.npmjs.com/files/package.json#license) (npm also allows "SEE LICENSE IN <filename>" and "UNLICENSED" for weirdly- or non-licensed stuff)?

**Comment by RichardLitt** [comment]
Yes, it should refer to SPDX. I will change that.
