### ISSUE TITLE
Clarify the difference between examples and usage

### ISSUE THREAD

**Issue by Mouvedia** [RichardLitt/standard-readme#79]
Should a README have an Examples section separate from the Usage section?
Are examples just sub-sections under Usage?
What was the convention used in man pages? Does your definition match it?
What's your take on SYNOPSIS? (use cases)

**Comment by wooorm** [comment]
This spec does not define an examples heading. It defines a Usage section, which should be an example of basic, common use. In my understanding it should be all possible examples.
Examples can be added in the “Extra sections” placeholder though.

> What was the convention used in man pages? Does your definition match it?

This is not something the standard-readme spec is concerned with. To my knowledge there is no standard for man pages.

> What's your take on SYNOPSIS? (use cases)

Synopsis is a man page heading, which is a more like an API signature typically found in readmes. E.g, for JS APIs, a signature could look like this: `print(value[, options])`. In SR, these go in the API section.
