### ISSUE TITLE
make it less js specific?

### ISSUE THREAD

**Issue by jbenet** [RichardLitt/standard-readme#8]
There's a lot of js-specific stuff. would be great to use this across languages. maybe qualify suggestions with the language it applies to. same goes for package managers, etc.

**Comment by RichardLitt** [comment]
Yes! Agreed on this.

**Comment by RichardLitt** [comment]
Ok, I think I've managed that. What do you think?

**Comment by RichardLitt** [comment]
This is a rolling issue; since it is not actionable, I will close it now. If anyone has any specific suggestions, open a new issue about language specificity.
