### ISSUE TITLE
Rename "Contribute" section to "Contributing"

### ISSUE THREAD

**Issue by davidak** [RichardLitt/standard-readme#84]
Is there a reason why you use "Contribute"? I found no discussion in the issues.

"Contributing" is a common name for such a section.

Most guides i found use it, for example:

* https://www.makeareadme.com/
* https://github.com/davidbgk/open-source-template/blob/master/README.md
* https://rowanmanning.com/posts/writing-a-friendly-readme/
* https://gist.github.com/PurpleBooth/109311bb0361f32d87a2
* https://changelog.com/posts/top-ten-reasons-why-i-wont-use-your-open-source-project
* https://github.com/LappleApple/feedmereadmes/blob/master/README-maturity-model.md
* https://medium.com/@NSomar/readme-md-history-and-components-a365aff07f10
* https://gist.github.com/zenorocha/4526327

only a few use "Contribute":

* https://github.com/RichardLitt/standard-readme/blob/master/spec.md
* https://github.com/bevry/projectz
* https://github.com/noffle/common-readme/blob/master/template.md

It is also widely used in readmes i found suggested as good examples:

* https://github.com/gollum/gollum
* https://github.com/jakubroztocil/httpie
* https://github.com/showdownjs/showdown
* https://github.com/requests/requests
* https://github.com/kaminari/kaminari
* https://github.com/anfederico/Clairvoyant
* https://github.com/athityakumar/colorls
* https://github.com/github-changelog-generator/github-changelog-generator
* https://github.com/karan/joe
* https://github.com/nhnent/tui.editor
* https://github.com/ryanoasis/nerd-fonts
* https://github.com/shama/gaze
* https://github.com/sourcerer-io/sourcerer-app
* https://github.com/teles/array-mixer
* https://github.com/webpro/release-it

I actually found none that use "Contribute". I checked for also every example of [awesome-readme](https://github.com/matiassingers/awesome-readme#examples). Sadly many readmes don't have this section at all!

An important point is probably also that GitHub points to the CONTRIBUTING file. See https://help.github.com/articles/setting-guidelines-for-repository-contributors/#adding-a-contributing-file

This change would help to standardize readmes.

**Comment by RichardLitt** [comment]
> An important point is probably also that GitHub points to the CONTRIBUTING file. See help.github.com/articles/setting-guidelines-for-repository-contributors/#adding-a-contributing-file

This is probably the biggest point in favor of the change. I keep messing up the name of the Contributing file, instead writing Contribute. Changing it would make this easier. 

Want to make a PR for all of these changes?
