### ISSUE TITLE
Rename "Install" section to "Installation" (again)

### ISSUE THREAD

**Issue by davidak** [RichardLitt/standard-readme#85]
What was the reason to rename it in https://github.com/RichardLitt/standard-readme/commit/2986c499017e94aa991e93180e717f5a80e44ca2?

"Installation" is commonly used, but it's not that clear as with "Contributing". https://github.com/RichardLitt/standard-readme/issues/84

All guides and examples that use "Contributing" in the linked issue also use "Installation".

Here are some examples i found that use "Install" and "Contributing":

* https://github.com/zcei/standard-readme
* https://github.com/nhnent/tui.editor
* https://github.com/jehna/readme-best-practices/blob/master/README-default.md
* https://github.com/scrapy/scrapy

A point for this change would be that no other section is named in an imperative manner. (when Contribute is also renamed). I think that would make it more consistent and helps standardize readmes.

**Comment by RichardLitt** [comment]
I prefer Install. I think it's easier to read. :)

**Comment by davidak** [comment]
That's fine. Thanks
