### ISSUE TITLE
Spec assumes English is included in all multi-lingual projects

### ISSUE THREAD

**Issue by nikcorg** [RichardLitt/standard-readme#90]
The [spec](https://github.com/RichardLitt/standard-readme/blame/master/spec.md#L9) says:

> Where there are multiple languages, `README.md` is reserved for English.

This assumes English is always included as one of the languages in a multi-lingual project. I would suggest rephrasing to:

> Where there are multiple languages, and they include the English languge, `README.md` is reserved for English.

Or if indeed the intention is to say that only the English language should have the priviledge of omitting the language specifier from the filename in a multi-lingual project, it should be stated as such, but I'm assuming this is not the sought-after message.

**Comment by RichardLitt** [comment]
I think this makes sense. But - isn't README an English term? Shouldn't we ask for other languages to use their own terms for this file, if the content isn't in English?

**Comment by nikcorg** [comment]
That is in conflict with the spec, which stipulates that the file is called `README.md`.

**Comment by RichardLitt** [comment]
Yes. I'm suggesting changing the specification: README, is, of course, English. If you're suggesting allowing the content to be in another language, than the title should also change. I think keeping README as an English document by default makes the most sense.

**Comment by nikcorg** [comment]
I think having a standard name is sensible, as then the files will all be adjacent to each other when listed.

**Comment by RichardLitt** [comment]
Fair. But I'm not sure that README should be that name, if there isn't an English one. I'm happy with the spec as it is, I think. Thank you.
