### ISSUE TITLE
Add support for CHANGELOG.md?

### ISSUE THREAD

**Issue by talltom** [RichardLitt/standard-readme#92]
I frequently use a CHANGELOG.md file to document release notes for specific versions of a project. I then link to this in the README, normally in the contributing section (e.g. "please update the changelog when releasing a version").

I find that a stand alone document is complimentary to git tags we use for versioning.

Here is an example: https://github.com/urbanriskmap/cognicity-server/blob/master/CHANGELOG.md

I'm interested whether there is appetite to add this as an optional section/link (as per API.md).

**Comment by wooorm** [comment]
I personally host my changelogs in GitHub Releases. Such as like so in [wooorm/lowlight](https://github.com/wooorm/lowlight/releases). Recently GH added support for watching a repo for releases, so I think more people will start using it.

I’m personally not in favour of requiring the `changelog.md` file, but the section in the readme is 👍

**Comment by RichardLitt** [comment]
I think this would be a good idea to have, but I'm not sure it needs to have its own section. Thank you for the suggestion! I am going to close this; but, if a lot of other people star this over the coming years, we can think about adding it. 

Thank you so much for your suggestion.
