### ISSUE TITLE
Add a Credits/Thanks/Acknowledgements section

### ISSUE THREAD

**Issue by dominiksalvet** [RichardLitt/standard-readme#94]
Hello everyone, I would like to start a discussion of adding Credits/Thanks/Acknowledgements section to the Standard Readme [specification](https://github.com/RichardLitt/standard-readme/blob/master/spec.md) - its advantages and disadvantages. What do you think? :smiley:

Personally, I found out that the words `Credit[s]` and `Thank[s]` are entirely missing in the whole specification and that is unfortunate. I think that those sections would provide a way for developers to say 'Thank you!' - whoever/whatever is a recipient of the message. And I think that this behaviour should be encouraged directly by the specification, yet optional of course.

If it didn't make it as an individual optional section, I would propose adding it to a Suggestion section's list, e.g., in Extra section as an example.

**Comment by wooorm** [comment]
I’ve done a section similar to `thanks` but called [`acknowledgements`](https://github.com/unifiedjs/unified#acknowledgments)

**Comment by dominiksalvet** [comment]
@wooorm I don't insist on one of my names, yours is great as well! :-) Also, the content of your section is something I would imagine.

**Comment by dominiksalvet** [comment]
Guys, please, do not let me down. :smiley: What is your opinion? What do you think?

**Comment by dominiksalvet** [comment]
Well, I am using `Thanks` section in the meantime as stated in [asus-fan-control](https://github.com/dominiksalvet/asus-fan-control). It is shorter than two others, that's why... :smiley:

**Comment by RichardLitt** [comment]
> And I think that this behaviour should be encouraged directly by the specification, yet optional of course.

I highly approve of this. Make a PR! This should be encouraged! Thank you!

> Guys, please, do not let me down. 😃 What is your opinion? What do you think?

If you meant me, :wave:. Sometimes it takes me a while to respond. :)

**Comment by dominiksalvet** [comment]
@RichardLitt Thank you very much for your opinion! :+1: I will make a PR. Guys, please review the PR whether everything is fine. Feel free to make changes to the PR. I hope I didn't forget anything. :smiley:
