### ISSUE TITLE
Examples use "contributing" which results in an error

### ISSUE THREAD

**Issue by lukasoppermann** [RichardLitt/standard-readme#98]
Hey,

recently "contribute" was changed to "contributing", however the linter was not updated, so it throws an error.

https://github.com/RichardLitt/standard-readme/blob/master/example-readmes/minimal-readme.md#contributing

**Comment by RichardLitt** [comment]
Good catch. Do you want to open a PR to fix it, so you get more attribution?

**Comment by lukasoppermann** [comment]
Hey, I am fine without the attribution. 😁Also I currently have no idea where I need to change it and which one is correct.

**Comment by RichardLitt** [comment]
This shoud be done.
